services:
  ellery:
    image: ghcr.io/wilymonkey/ellery:latest
    container_name: ellery
    ports:
      - "3000:3000"
    environment:
      DB_FILE_NAME: "db.sqlite"
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_NUMBER: ""
